name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Start backend and frontend
        run: |
          npm run build
          npm run start &
          sleep 10

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_valid_username: admin
          CYPRESS_valid_password: AdminPass1
          CYPRESS_invalid_password: incorrectpass

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run postman/Tests.postman_collection.json
